### ISSUE TITLE
Issue with some Drop down Field types (status)

### ISSUE THREAD

**Issue by andymain** [AlexaCRM/php-crm-toolkit#6] opened 2016-10-24 10:04 UTC
Entity.php line 641
When you have a $propertyDetails->type = 'status'
The OptionSet Label is passed through to the API SOAP Call instead of the value. This cause a SOAP fault as an integer not a string is expected;

"The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:entity. The InnerException message was 'There was an error deserializing the object of type Microsoft.Xrm.Sdk.Entity. The value 'New Enquiry' cannot be parsed as the type 'Int32'.'. Please see InnerException for more details. in xxxxxx/vendor/alexacrm/php-crm-toolkit/src/Client.php:1202"

**Comment by georged** [comment] 2016-10-24 11:24
@andymain looks like you are assigning a text value instead of int32. Not sure what the expectations are here - it's caller's responsibility to "translate" between optionset text and int values and pass integer as a value and not text. Can you post a fragment of code generating the error to confirm if it's a bug or not?

**Comment by andymain** [comment] 2016-10-25 08:46
Hi, I'm definitely passing the int value through, this then gets translated to the text label contained within the OptionSet somewhere between the Entity->create() and where the XML for the API call is generated.

I'll post up some further information with code fragments etc.

**Comment by georged** [comment] 2016-10-25 08:50
Then it sounds like a bug. Give us the code fragment causing the drama, we'll try to reproduce. 
Also, are you using it straight on a custom php page or as part of the [plugin](wordpress.org/plugins/integration-dynamics)?

**Comment by andymain** [comment] 2016-10-26 14:12
Hi please see the below; the chunk of code that's erroring, full stack trace, debug of the attributes being passed into $entity->create() [You can see the INT being passed], and debug of the resulting XML produced for the call [You can see the incorrectly translated String], let me know if you need anything else.

```php
private function createResponse($attributes, $module_name = 'lead') {     
$this->connect();      
$response = $this->client->entity($module_name);     

foreach ($attributes as $key => $value) {         
$response->{$key} = $value;     
}      
$responseId = $response->create();      

$result = (object)[ 'id' => $responseId,  'status' => 'created',];     

 return $result;  
}
```

[2016-10-26 12:35:57] local.ERROR: SoapFault exception: [s:Sender] The formatter threw an exception while trying to deserialize the message: There was an error while trying to deserialize parameter http://schemas.microsoft.com/xrm/2011/Contracts/Services:entity. The InnerException message was 'There was an error deserializing the object of type Microsoft.Xrm.Sdk.Entity. The value 'Contacted' cannot be parsed as the type 'Int32'.'.  Please see InnerException for more details. in /home/vagrant/git/gecko-api/vendor/alexacrm/php-crm-toolkit/src/Client.php:1202
Stack trace:
#0 /home/vagrant/git/gecko-api/vendor/alexacrm/php-crm-toolkit/src/Client.php(1662): AlexaCRM\CRMToolkit\Client::getSoapResponse('https://testnap...', '<s:Envelope xml...')
#1 /home/vagrant/git/gecko-api/vendor/alexacrm/php-crm-toolkit/src/Entity.php(444): AlexaCRM\CRMToolkit\Client->create(Object(AlexaCRM\CRMToolkit\Entity))
#2 /home/vagrant/git/gecko-api/app/Integrations/NewDynamics.php(462): AlexaCRM\CRMToolkit\Entity->create()
#3 /home/vagrant/git/gecko-api/app/Integrations/NewDynamics.php(403): Gecko\Integrations\NewDynamics->createResponse(Array, 'lead')

Int attribute being passed
<img width="1179" alt="screen shot 2016-10-26 at 14 44 50" src="https://cloud.githubusercontent.com/assets/1101889/19728735/727b0ab6-9b8c-11e6-9e42-aed0dd4b9b34.png">

Incorrect String translated into XML for call
<img width="2553" alt="screen shot 2016-10-26 at 14 52 31" src="https://cloud.githubusercontent.com/assets/1101889/19728746/7854ca6c-9b8c-11e6-8f25-ae20fdebf1e0.png">

**Comment by wizardist** [comment] 2016-10-26 14:41
@andymain I can bet this is caused by trying to put `OptionSetValue` (`$this->propertyValues[ $property ]['Value']`) in `appendChild` which invokes object-to-string conversion via `__toString()` which in its turn produces a label, not a numerical value.

Issue identified and will be fixed very soon. Thanks for debugging, you've done a great job!

**Comment by wizardist** [comment] 2016-10-26 16:46
@andymain please update the package via Composer and try again.

**Comment by andymain** [comment] 2016-10-27 08:50
That's great the status type dd now functions as expected when being passed through, thanks for the help.

**Closed** 2016-10-27 10:37 UTC
Labels: bug
